# This file was generated by GoReleaser. DO NOT EDIT.
cask "ksail-desktop" do
  version "7.183.4"

  on_macos do
    on_arm do
      sha256 "5738288e83dbdf0fd34090bb07f396d0a0714752518ef321eef68fa7db593e5a"
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/KSail_#{version}_darwin_arm64.zip"
    end
  end

  name "ksail-desktop"
  desc "Native desktop app to manage local Kubernetes clusters"
  homepage "https://ksail.devantler.tech/"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on macos: :big_sur

  app "KSail.app"
  binary "#{appdir}/KSail.app/Contents/MacOS/ksail-desktop"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/KSail.app"]
    end
  end

  uninstall quit: "tech.devantler.ksail.desktop"

  # No zap stanza required
end
