# This file was generated by GoReleaser. DO NOT EDIT.
cask "ksail" do
  version "7.200.1"

  on_macos do
    on_intel do
      sha256 :no_check
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_darwin_arm64.tar.gz"
      depends_on arch: :arm64
    end
  end
  on_macos do
    on_arm do
      sha256 "fff8edefd888bc58534f6b6ae12e9272b9d5ad40f4c65aca97480e2dea2a9e41"
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9c176217e4c66cb422e694504920c4dff4498637b2f0c3a62dededf0d7d44296"
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e33105e96cc2fb6afce61e0bd0a656d7f33e8ba310634ab6497892ce3013dd59"
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ksail"
  desc "CLI tool to manage Kubernetes clusters and workloads"
  homepage "https://ksail.devantler.tech/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ksail"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ksail"]
    end
  end

  # No zap stanza required
end
