# This file was generated by GoReleaser. DO NOT EDIT.
cask "ksail-desktop" do
  version "7.139.0"

  name "ksail-desktop"
  desc "Native desktop app to manage local Kubernetes clusters"
  on_macos do
    on_arm do
      sha256 "aa196275d3c5dd43bb4e6bf0871a9a6d7b60d1e00feabfee39e1113a9e0279a2"
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/KSail_#{version}_darwin_arm64.zip",
          verified: "github.com/devantler-tech/ksail/"
    end
  end

  homepage "https://ksail.devantler.tech/"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on macos: :big_sur

  app "KSail.app"
  binary "#{appdir}/KSail.app/Contents/MacOS/ksail-desktop"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/KSail.app"] if OS.mac?
  end

  # No zap stanza required
end
