# This file was generated by GoReleaser. DO NOT EDIT.
cask "ksail-desktop" do
  depends_on macos: :big_sur
  app "KSail.app"

  version "7.102.0"

  on_macos do
    on_arm do
      sha256 "3c36b37b2a31f62c45c453daf21095528a533aa6cf96fb6ba153b17cb514013f"
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/KSail_#{version}_darwin_arm64.zip",
        verified: "github.com/devantler-tech/ksail/"
    end
  end

  name "ksail-desktop"
  desc "Native desktop app to manage local Kubernetes clusters"
  homepage "https://ksail.devantler.tech/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "#{appdir}/KSail.app/Contents/MacOS/ksail-desktop"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/KSail.app"] if OS.mac?
  end

  # No zap stanza required

end
