# This file was generated by GoReleaser. DO NOT EDIT.
cask "ksail" do
  on_macos do
    on_intel do
      sha256 :no_check
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_darwin_arm64.tar.gz"
      depends_on arch: :arm64
    end
  end
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ksail"]
    end
  end

  version "7.198.22"

  on_macos do
    on_arm do
      sha256 "506e1bbb9cb58cbead52349310876c4d610abb6bc679ee7443328a141f49aaf3"
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c46d7a625120338625e8ea899dc8a39e48bd68a3f60c13d6c4302c1f155583b9"
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c0e87118c47f4a0c828e8582238e7a06f72b6c2c3c86ef605e2b81898e62586"
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ksail"
  desc "CLI tool to manage Kubernetes clusters and workloads"
  homepage "https://ksail.devantler.tech/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ksail"

  # No zap stanza required
end
