# This file was generated by GoReleaser. DO NOT EDIT.
cask "ksail" do
  name "ksail"
  desc ""
  homepage ""
  version "5.73.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ksail"

  on_macos do
    on_arm do
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_darwin_arm64.tar.gz"
      sha256 "14815ed6de32c6b53108b59b3137629e387abbbaba604f99d7b97c79a7f98dc5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_linux_amd64.tar.gz"
      sha256 "29cd09cd04601f802789f958cf320813f4c6abb304512a40a152d1dc44b77da8"
    end
    on_arm do
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_linux_arm64.tar.gz"
      sha256 "578878971c3abfcd5efa6749138bf68e05bfadc414dab34ed96b798748a487d6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ksail"]
    end
  end

  # No zap stanza required
end
