# This file is generated by World at Ruin's CD workflow. DO NOT EDIT.
cask "world-at-ruin" do
  version "0.65.4"
  sha256 "e0e2b3c91595ed1eac13ea58bc11e5fabae5b5b098a4c5e036c153f5d61149fb"

  # No verified: parameter here. brew audit --strict rejects it when
  # the download domain matches the homepage domain, which it does
  # here (both github.com). ksail needs it only because its homepage
  # is a separate site.
  url "https://github.com/devantler-tech/world-at-ruin/releases/download/v#{version}/WorldAtRuin-#{version}-macOS-universal.zip"
  name "World at Ruin"
  desc "Cloud-native MMORPG built almost entirely by agents"
  homepage "https://github.com/devantler-tech/world-at-ruin/"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on macos: :big_sur

  app "World at Ruin.app"

  postflight do
    # The build is AD-HOC signed (Godot's built-in codesign, no
    # Developer ID), so Gatekeeper quarantines it on download and it
    # will not launch without this.
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/World at Ruin.app"]
  end

  uninstall quit: "tech.devantler.worldatruin"

  zap trash: "~/Library/Application Support/Godot/app_userdata/World at Ruin"
end
