---
name: CI

on:
  pull_request:
  merge_group:

permissions: {}

jobs:
  required-checks:
    name: CI - Required Checks
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Aggregate job checks
        uses: devantler-tech/actions/aggregate-job-checks@10429850e4620adb409e568bab16ba1bbe36a4b5 # v3.4.0
        with:
          job-results: ""
