---
name: CI

on:
  pull_request:
  merge_group:

permissions: {}

jobs:
  required-checks:
    name: CI - Required Checks
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Aggregate job checks
        uses: devantler-tech/actions/aggregate-job-checks@3556694b57702d81bfc5fb1d79a9ee0b4e53aca7 # v5.0.0
        with:
          job-results: ""
